name: Azure Pipelines

trigger:
- main

pool: myPool

variables:
  python.version: '3.7.6'
  azureServiceConnectionId: 'ab43008d-e2a5-42e0-a87d-5fdbd6912c81'
  projectRoot: $(System.DefaultWorkingDirectory)
  subscriptionId: 'a785336a-35d8-4efd-80be-93d34a9e4b66'
  resourceGroupName: 'Azuredevops'
  armBackendStorageAccountName: 'tfstate91224001'
  armBackendContainerName: 'tfstate'
  packerImageName: 'myPackerImage'
  environmentName: 'myEnvironment'
  azureWebAppName: 'webapp-0254563186.azurewebsites.net'

stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    - script: |
        echo "==== BEGIN: File list for $(Build.BuildId) ===="
        find . -type f
      displayName: 'Log files at beginning of stage'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Terraform installation'
      inputs:
        terraformVersion: '1.2.9'

    - script: |
        echo "ARM_ACCESS_KEY is set: ${ARM_ACCESS_KEY:+yes}"
      displayName: "Check ARM_ACCESS_KEY presence"
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: '$(resourceGroupName)'
        backendAzureRmStorageAccountName: '$(armBackendStorageAccountName)'
        backendAzureRmContainerName: '$(armBackendContainerName)'
        backendAzureRmKey: 'test.terraform.tfstate'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: Terraform check vars
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-var-file="$(Agent.TempDirectory)/terraform.tfvars" -out="azure.plan"'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    # - task: InstallSSHKey@0
    #   condition: false
    #   inputs:
    #     knownHostsEntry: 'KNOWN_HOSTS_STRING'
    #     sshPublicKey: 'PUBLIC_KEY'
    #     sshKeySecureFile: 'udacity_rsa'

    # - task: DownloadSecureFile@1
    #   condition: false
    #   name: udacity_public_key
    #   displayName: 'Download public key'
    #   inputs:
    #     secureFile: 'public.key'

    - task: DownloadSecureFile@1
      displayName: 'Download tfvars from Azure Files'
      inputs:
        secureFile: 'terraform.tfvars'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      condition: false
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'azure.plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    - task: TerraformTaskV3@3
      condition: false
      displayName: Terraform destroy
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

    - task: ArchiveFiles@2
      displayName: 'Archive UI Tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip
      displayName: 'Upload Package'
      artifact: drop-ui-tests

    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi

    - task: ArchiveFiles@2
      displayName: 'Archive PerformanceTestSuite'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/testsuite'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-tests.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-tests.zip
      displayName: 'Upload Package'
      artifact: drop-jmeter-tests

  - job: AutomatedTesting
    condition: true
    displayName: Automated Testing
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: |
          sudo apt install nodejs -y
          sudo apt install npm -y
          sudo npm install -g newman
        workingDirectory: $(System.DefaultWorkingDirectory)

    - task: CmdLine@2
      displayName: Run Postman Tests
      continueOnError: true
      inputs:
        script: 'newman run Udacity.postman_collection.json -e environment.json --reporters cli,junit --reporter-junit-export postman.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/postman.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
        mergeTestResults: true
        testRunTitle: test-run-$(Build.BuildId)
    - script: |
        echo "==== END: Files at Build end ===="
        find . -type f
      displayName: 'Log files at end of Build stage'
#--------------------------------------------#  
# DEPLOYMENT STAGE
#--------------------------------------------#    
- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool:
      name: 'myPool'
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "==== BEGIN: Files at DEPLOY end ===="
              find . -type f
            displayName: 'Log files at end of DEPLOY stage'
          - task: AzureWebApp@1
            condition: false
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: 'myWebApp'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
          - script: |
              echo "==== END: Files at DEPLOY end ===="
              find . -type f
            displayName: 'Log files at end of DEPLOY stage'
#--------------------------------------------#  
# SELENIUM TESTS STAGE
#--------------------------------------------#    
- stage: SeleniumTests
  jobs:
  - deployment: VMDeploy
    pool:
      name: 'myPool'
    displayName: Selenium Tests
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop-ui-tests
          - script: |
              echo "==== BEGIN: Files at TEST start ===="
              find . -type f
            displayName: 'Log files at end of TEST stage'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                cd ~/
                DIR=/home/testuser/app
                if [ ! -d "$DIR" ]; then
                    mkdir app
                fi
                mv /home/testuser/azagent/_work/1/drop-uitests/$(Build.BuildId)-uitests.zip app
                cd app
                unzip -o $(Build.BuildId)-uitests.zip
                FILE=/home/testuser/app/chromedriver_linux64.zip
                if [ ! -f "$FILE" ]; then
                    LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
                    wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
                    unzip -o chromedriver_linux64.zip
                    sudo ln -s $PWD/chromedriver /usr/local/bin/chromedriver
                fi
                export PATH=$PATH:/home/testuser/app
                echo "Starting Selenium Tests"
                python3 main.py >> selenium.log
                echo "Completed Selenium Tests. Check selenium.log for results."
          - script: |
              echo "==== END: Files at TEST end ===="
              find . -type f
            displayName: 'Log files at end of TEST stage'



#--------------------------------------------#  
# JMETER TESTS STAGE
#--------------------------------------------#    
- stage: SeleniumTests
  jobs:
  - deployment: VMDeploy
    pool:
      name: 'myPool'
    displayName: JMeter Tests
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop-jmeter-tests
          - script: |
              unzip -o $(Pipeline.Workspace)/drop-jmeter-tests/$(Build.BuildId)-jmeter-tests.zip -d jmeter-tests
            displayName: 'Unzip JMeter Tests'
          - script: |
              wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.2.1.tgz
              tar -xf apache-jmeter-5.2.1.tgz
              sudo mv apache-jmeter-5.2.1 /opt/jmeter
              sudo ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter
            displayName: 'Install JMeter'
          - script: |
              cd jmeter-tests/automatedtesting/jmeter
              jmeter -n \
                -t endurance.jmx \
                -JbaseUrl=fakerestapi.azurewebsites.net \
                -l test-results.csv \
                -e -o html/endurance
            displayName: 'Run endurance test'
          - script: |
              cd jmeter-tests/automatedtesting/jmeter
              jmeter -n \
                -t stress.jmx \
                -JbaseUrl=fakerestapi.azurewebsites.net \
                -l test-results.csv \
                -e -o html/stress
            displayName: 'Run stress test'
          - publish: jmeter-tests/automatedtesting/jmeter/html
            artifact: jmeter-report
            displayName: 'Publish JMeter HTML Report'
          - script: |
              echo "==== END: Files at TEST end ===="
              find . -type f
            displayName: 'Log files at end of TEST stage'