name: Azure Pipelines

trigger:
- main

pool: myPool

variables:
  python.version: '3.7.6'
  azureServiceConnectionId: '9797b99f-0a8f-4f21-9469-31c27100fe58'
  projectRoot: $(System.DefaultWorkingDirectory)
  subscriptionId: '0fadec41-9b39-430f-aa5d-ce7b49f9346c'
  resourceGroupName: 'Azuredevops'
  armBackendStorageAccountName: 'tfstate207391737'
  armBackendContainerName: 'tfstate'
  packerImageName: 'myPackerImage'
  environmentName: 'myEnvironment'
  azureWebAppName: 'webapp-odluser284939'
  webAppUrl: 'webapp-odluser284939.azurewebsites.net'

stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Terraform installation'
      inputs:
        terraformVersion: '1.2.9'

    - script: |
        echo "ARM_ACCESS_KEY is set: ${ARM_ACCESS_KEY:+yes}"
      displayName: "Check ARM_ACCESS_KEY presence"
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: '$(resourceGroupName)'
        backendAzureRmStorageAccountName: '$(armBackendStorageAccountName)'
        backendAzureRmContainerName: '$(armBackendContainerName)'
        backendAzureRmKey: 'test.terraform.tfstate'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      condition: true
      displayName: Terraform check vars
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-var-file="$(Agent.TempDirectory)/terraform.tfvars" -out="azure.plan"'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    # - task: InstallSSHKey@0
    #   condition: false
    #   inputs:
    #     knownHostsEntry: 'KNOWN_HOSTS_STRING'
    #     sshPublicKey: 'PUBLIC_KEY'
    #     sshKeySecureFile: 'udacity_rsa'

    # - task: DownloadSecureFile@1
    #   condition: false
    #   name: udacity_public_key
    #   displayName: 'Download public key'
    #   inputs:
    #     secureFile: 'public.key'

    - task: DownloadSecureFile@1
      displayName: 'Download tfvars from Azure Files'
      inputs:
        secureFile: 'terraform.tfvars'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      condition: true
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'azure.plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

    - task: TerraformTaskV3@3
      condition: false
      displayName: Terraform destroy
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi

    - task: ArchiveFiles@2
      displayName: 'Archive UI Tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-ui-tests.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-ui-tests.zip
      displayName: 'Upload Package'
      artifact: drop-ui-tests

    - task: ArchiveFiles@2
      displayName: 'Archive PerformanceTestSuite'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/test-suite'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-tests.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-jmeter-tests.zip
      displayName: 'Upload Package'
      artifact: drop-jmeter-tests

    - task: ArchiveFiles@2
      displayName: 'Archive Postman Tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-postman-tests.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-postman-tests.zip
      displayName: 'Upload Package'
      artifact: drop-postman-tests



#--------------------------------------------#  
# DEPLOYMENT STAGE
#--------------------------------------------#    
- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool:
      name: 'myPool'
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: drop-fakerestapi
              path: $(Pipeline.Workspace)/drop-fakerestapi
          - task: AzureWebApp@1
            condition: true
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: '$(azureWebAppName)'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
          # - script: |
          #     echo "Health check"
          #     curl -s -o /dev/null -w "%{http_code}" $(webAppUrl)/api/Activities



#--------------------------------------------#  
# SELENIUM TESTS STAGE
#--------------------------------------------#    
- stage: SeleniumTests
  jobs:
  - deployment: SeleniumDeploy
    pool:
      name: 'myPool'
      vmImage: 'ubuntu-22.04'
    displayName: Selenium Tests
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: drop-ui-tests
              path: $(Pipeline.Workspace)/drop-ui-tests
          - script: |
              unzip -o $(Pipeline.Workspace)/drop-ui-tests/$(Build.BuildId)-ui-tests.zip -d $(Pipeline.Workspace)/drop-ui-tests/ui-tests
            displayName: 'Unzip Selenium Tests'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                pip3 install selenium
                cd $(Pipeline.Workspace)/drop-ui-tests/ui-tests
                rm -f selenium.log
                echo "Running tests..."
                python3 main.py --headless >> selenium.log
          - script: cat $(Pipeline.Workspace)/drop-ui-tests/ui-tests/selenium.log
            displayName: 'Print Selenium Log to Pipeline'
          - publish: $(Pipeline.Workspace)/drop-ui-tests/ui-tests/selenium.log
            artifact: selenium-report
            displayName: 'Publish Selenium Reports'



#--------------------------------------------#  
# POSTMAN TESTS STAGE
#--------------------------------------------#    
- stage: PostmanTests
  jobs:
  - deployment: PostmanDeploy
    pool:
      name: 'myPool'
    displayName: Postman Tests
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: drop-postman-tests
              path: $(Pipeline.Workspace)/drop-postman-tests
          - script: |
              unzip -o $(Pipeline.Workspace)/drop-postman-tests/$(Build.BuildId)-postman-tests.zip -d $(Pipeline.Workspace)/drop-postman-tests/postman-tests
            displayName: 'Unzip Postman Tests'
          - script: |
              sudo apt-get remove -y libnode-dev nodejs npm || true
              sudo apt-get autoremove -y || true
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs

              # Ensure old node binary isn't being used
              echo "Before fix: $(which node) -> $(node -v)"
              sudo ln -sf /usr/bin/node /usr/local/bin/node
              sudo ln -sf /usr/bin/npm /usr/local/bin/npm

              which node
              node -v
              npm -v
              sudo apt install -y npm
              sudo npm install -g newman
              newman -v
            displayName: 'Install newman'
          - script: |
              cd $(Pipeline.Workspace)/drop-postman-tests/postman-tests
              rm -rf postman.xml
              newman run Udacity.postman_collection.json \
                -e environment.json \
                --env-var "baseUrl=$(webAppUrl)" \
                --reporters cli,junit \
                --reporter-junit-export postman.xml
            displayName: 'Run postman regression and validation tests'
          - script: |
              cat $(Pipeline.Workspace)/drop-postman-tests/postman-tests/postman.xml
            displayName: 'Print Postman Reports'
          - publish: $(Pipeline.Workspace)/drop-postman-tests/postman-tests/postman.xml
            artifact: postman-report
            displayName: 'Publish Postman Report'



#--------------------------------------------#  
# JMETER TESTS STAGE
#--------------------------------------------#    
- stage: JMeterTests
  jobs:
  - deployment: JMeterDeploy
    pool:
      name: 'myPool'
    displayName: JMeter Tests
    environment: 'myEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: drop-jmeter-tests
              path: $(Pipeline.Workspace)/drop-jmeter-tests
          - script: |
              unzip -o $(Pipeline.Workspace)/drop-jmeter-tests/$(Build.BuildId)-jmeter-tests.zip -d $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests
            displayName: 'Unzip JMeter Tests'
          - script: |
              wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.2.1.tgz
              tar -xf apache-jmeter-5.2.1.tgz
              sudo mv apache-jmeter-5.2.1 /opt/jmeter
              sudo ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter
              sudo apt-get update
              sudo apt-get install -y openjdk-11-jdk
              export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
            displayName: 'Install JMeter'
            env:
              SYSTEM_DEBUG: true
          - script: |
              export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
              rm -rf $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/endurance
              mkdir -p $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/endurance/html
              cd $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/endurance
              jmeter -n \
                -t endurance.jmx \
                -JbaseUrl=$(webAppUrl) \
                -l $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/endurance/test-results.csv \
                -e -o $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/endurance/html \
                -j $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/endurance/jmeter.log
                
              echo "Print Endurance JMeter log"
              cat $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/endurance/jmeter.log
            displayName: 'Run endurance test'
          - script: |
              export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
              rm -rf $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/stress-test
              mkdir -p $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/stress-test/html
              cd $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/stress-test
              jmeter -n \
                -t stress.jmx \
                -JbaseUrl=$(webAppUrl) \
                -l $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/stress-test/test-results.csv \
                -e -o $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/stress-test/html \
                -j $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/stress-test/jmeter.log
              
              echo "Print Stress JMeter log"
              cat $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results/stress-test/jmeter.log
            displayName: 'Run stress test'
            env:
              SYSTEM_DEBUG: true
          - publish: $(Pipeline.Workspace)/drop-jmeter-tests/jmeter-tests/results
            artifact: jmeter-report
            displayName: 'Publish JMeter HTML Reports'


