variable location {}
variable resource_group {}
variable subnet_id {}
variable vm_count {}
variable prefix {}
variable tag_name {}
variable tag_value {}
variable admin_username {}
variable public_key {}